### PR TITLE
wf-details: show the logs of the workflow engine

### LINKED ISSUE #166: ui: refine workflow logs
If the workflow fails at the workflow engine level, before starting any jobs, the UI shows no error logs. While you can get the complete logs with the client, it might be confusing for some users to see a failed workflow without any errors on the UI. 

Possible solutions

*  Show only the workflow engine logs if the workflow fails before creating jobs
* Add another tab (e.g. next to "Step") or option in drop down to show workflow  engine logs. Could be always present.

### PR DESCRIPTION
**Pull request by mdonadoni**
Closes #166

### CODE REVIEW

File: reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js [hunk 1]
```diff
@@ -21,15 +21,26 @@ import { CodeSnippet, TooltipIfTruncated } from "~/components";
...
-  const [selectedStep, setSelectedStep] = useState();
+function EngineLogs({ logs }) {
+  return logs ? (
+    <CodeSnippet dollarPrefix={false} classes={styles.logs}>
+      {logs}
+    </CodeSnippet>
+  ) : (
+    <Message
+      icon="info circle"
+      content="There are no workflow engine logs available."
```
Comment (audrium) [inline reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js:32]: Minor: perhaps "There are no workflow engine logs available yet." message would better inform users that it will soon be populated. Or we add a sentence describing that the logs will be shown once the workflow finishes

**Review by audrium — APPROVED** [review]
Works nicely! I personally like this approach to display the engine logs in a different tab.
I think it's better than trying to fit it along the job steps :+1: 
@tiborsimko please share your observations about this

File: reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js [hunk 2]
```diff
@@ -21,15 +21,26 @@ import { CodeSnippet, TooltipIfTruncated } from "~/components";
...
-  const [selectedStep, setSelectedStep] = useState();
+function EngineLogs({ logs }) {
+  return logs ? (
+    <CodeSnippet dollarPrefix={false} classes={styles.logs}>
+      {logs}
+    </CodeSnippet>
+  ) : (
+    <Message
+      icon="info circle"
+      content="There are no workflow engine logs available yet."
```
Comment (tiborsimko) [inline reana-ui/src/pages/workflowDetails/components/WorkflowLogs.js:32]: Whlist the workflow is running/queued/pending, it would be better to say something like:

- The workflow engine logs will be available after the workflow run finishes.

And, when there the execution finishes, usually there will be something, also for failed/stopped/etc runs. But if there is still nothing, we can display a generic message:

- There are no workflow engine logs for this execution run.

The motivation is simply to tell users when to expect logs to be visible.  ("yet" is too generic)

File: reana-ui/src/pages/workflowDetails/WorkflowDetails.js [hunk 3]
```diff
@@ -103,9 +103,17 @@ function WorkflowDetails() {
...
     {
-      menuItem: { key: "logs", icon: "terminal", content: "Logs" },
+      menuItem: { key: "job-logs", icon: "terminal", content: "Job Logs" },
       render: () => <WorkflowLogs id={workflow.id} />,
     },
+    {
+      menuItem: {
+        key: "engine-logs",
+        icon: "cogs",
+        content: "Engine Logs",
```
Comment (tiborsimko) [inline reana-ui/src/pages/workflowDetails/WorkflowDetails.js:113]: What about "Engine logs" case in the visible menu title,  to be consistent with BrE style rather than AmE style of title headings.

File: reana-ui/src/pages/workflowDetails/WorkflowDetails.js [hunk 4]
```diff
@@ -103,9 +103,17 @@ function WorkflowDetails() {
 
   const panes = [
     {
-      menuItem: { key: "logs", icon: "terminal", content: "Logs" },
+      menuItem: { key: "job-logs", icon: "terminal", content: "Job Logs" },
```
Comment (tiborsimko) [inline reana-ui/src/pages/workflowDetails/WorkflowDetails.js:106]: What about "Job logs" case in the visible menu title, to be consistent with BrE style rather than AmE style of title headings.
