### PR TITLE
fix(utils): update failed workflows duration using finished time

### LINKED ISSUE #386: ui: workflow duration keeps changing for failed workflows
When looking at the details of a failed workflow, either in the workflow list page or in the workflow details page, the workflow duration keeps updating as time goes by.

For example, in a workflow like this:
image

After refreshing the page (either manually or automatically by the REANA UI), the new duration will be different, e.g. `failed after 6h 12m 59s`. This should not happen, as that value indicates the duration of the workflow, and that's not supposed to change after the workflow terminates its execution (regardless of the status).

The issue seems to present itself only with failed workflows.

### PR DESCRIPTION
**Pull request by giuseppe-steduto**
- fix(utils): update failed workflows duration using finished time
  Fix the way in which the duration of failed workflows is calculated, to
  use the time at which the run was finished rather than the current time.

  Closes #386

- ci(shellcheck): exclude node_modules from the analyzed paths

### CODE REVIEW

**Review by mdonadoni — COMMENTED** [review]
Looks good!

What about the `fix(utils)` scope? @tiborsimko

**Review by mdonadoni — APPROVED** [review]
LGTM, but it needs a rebase!

File: run-tests.sh [hunk 1]
```diff
@@ -29,7 +29,7 @@ check_commitlint () {
 }
 
 check_shellcheck () {
-    find . -name "*.sh" -exec shellcheck {} \+
+    find . -name "*.sh" ! -path "./reana-ui/node_modules/*" -exec shellcheck {} \;
```
Comment (mdonadoni) [inline run-tests.sh:32]:
```suggestion
    find . -name "*.sh" ! -path "./reana-ui/node_modules/*" -exec shellcheck {} \+
```

Comment (mdonadoni) [reply run-tests.sh:32]: See https://github.com/reanahub/reana-ui/commit/7b5f29ebc604a2d27d76f8a51b437c3e561fec32
