### PR TITLE
wf-details: fix non-existing workflow display

### LINKED ISSUE #82: wf-details: show message when accesing unauthorized workflow details
**Current behavior**

Loader spinning forever.

**Expected behavior**

Message saying something like "Sorry you are not authorized to see this workflow"

### PR DESCRIPTION
**Pull request by mvidalgarcia**
fixes #82

### CODE REVIEW

File: reana-ui/src/pages/workflowDetails/WorkflowDetails.js [hunk 1]
```diff
@@ -45,20 +45,20 @@ function WorkflowDetails() {
...
   }
 
-  if (_.isEmpty(workflow)) {
+  if (!workflow) {
     return (
       <Container text className={styles.warning}>
         <Message
           icon="warning sign"
-          header="Workflow does not exist."
+          header="Sorry you are not authorised to see this workflow or does not exist."
```
Comment (tiborsimko) [inline reana-ui/src/pages/workflowDetails/WorkflowDetails.js]: "or it does not..."

Perhaps better said in the inverse order, "Sorry, this workflow either does not exist or you are not authorised to see it." I'll amend the PR accordingly.

P.S. In the future we should split these two cases, as it might cause confusion...
