### PR TITLE
actions: improve error handling

### LINKED ISSUE #155: ui: better exception handling
> The `reana-ui issue` on `0.7.0devYYYYMMDD` deployed on PROD that I mentioned at the stand-up today was the following:

>  - `reana-server` was not returning a response for a reason or another;
> - `reana-client` reported correctly an error in CLI;
> - ... but `reana-ui` showed default homepage, very fast, as if the user did not launch any workflows at all so far.

> The database was OK and the system came back to life after killing `r-server` and `r-w-controller`.

> Verify `reana-ui` exception handling on `maint-0.7` and see what happens with the web interface when `r-server` misbehaves, e.g. when it is not contactable?  It would be better if the front page "keep spinning", or shows an error, rather than the default "welcome" page.

_Originally reported by @tiborsimko on Mattermost_

### PR DESCRIPTION
**Pull request by mvidalgarcia**
- Avoids infinite loop of `fetchWorkflows` requests if config endpoint misbehaves (pollingSecs).
- Avoids displaying welcome page when an exception happens on server.
- Gets rid of all `fetch()` calls, replacing them with `axios` calls.

partially addresses #46
closes #155

### CODE REVIEW

File: reana-ui/src/actions.js [hunk 1]
```diff
@@ -151,20 +137,18 @@ export const userSignin = (formData) =>
...
 export function userSignout() {
   return async (dispatch) => {
-    let resp;
-    try {
-      dispatch({ type: USER_SIGNOUT });
-      resp = await fetch(USER_SIGNOUT_URL, {
-        method: "POST",
-        credentials: "include",
+    dispatch({ type: USER_SIGNOUT });
+
```
Comment (audrium) [inline reana-ui/src/actions.js:141]: Minor nitpick: this empty line could be removed

File: reana-ui/src/pages/workflowList/WorkflowList.js [hunk 2]
```diff
@@ -66,7 +66,7 @@ function Workflows() {
     };
   }, [config.pollingSecs, dispatch, pagination, reanaToken]);
 
-  if (!workflows) {
+  if (!workflows || !config.pollingSecs) {
```
Comment (audrium) [inline reana-ui/src/pages/workflowList/WorkflowList.js:69]: Minor suggestions: this logic could be moved to `selectors` just to be more declarative

**Review by audrium — APPROVED** [review]
Left couple of minor comments, but in overall it looks good to me! Much much better now compared with plain `fetch`!

File: reana-ui/src/pages/workflowList/WorkflowList.js (hunk 2 above)
Comment (mvidalgarcia) [reply reana-ui/src/pages/workflowList/WorkflowList.js:69]: Do you mean something like this?

```js
export const getWorkflows = (state) =>
  !!state.config.pollingSecs && state.workflows.workflows;
```

If yes.. I'm not sure.. for now we're only using getWorkflows in a single place, but if we start using it somewhere else it will always depend on the existence of `pollingSecs`, which I'm not sure if it's correct.

Comment (audrium) [reply reana-ui/src/pages/workflowList/WorkflowList.js:69]: Actually my initial thought was to move `!workflows || !config.pollingSecs` to selectors, but probably it's not the right place to keep it. Maybe we can create a new variable in the top of the component, something like `const showWelcomePage = !workflows || !config.pollingSecs;` and use this while rendering. It could increase readability a bit

Comment (mvidalgarcia) [reply reana-ui/src/pages/workflowList/WorkflowList.js:69]: Ah ok, I get your point now. Unfortunately, the polling is making our lives harder and harder. I'll create a variable as you suggest.

Comment (mvidalgarcia) [reply reana-ui/src/pages/workflowList/WorkflowList.js]: I've created a new selector called `isConfigLoaded` to be more accurate, instead of just checking `pollingSecs`. Let me know what you think. cc/ @audrium

Comment (audrium) [reply reana-ui/src/pages/workflowList/WorkflowList.js]: I like how it's implemented now! Just a thought: we could modify `config` reducer to hold a flag `isLoaded` or `isFetched` and use that flag in the `isConfigLoaded` `selector`. What do you think?

Comment (mvidalgarcia) [reply reana-ui/src/pages/workflowList/WorkflowList.js]: That's indeed better than comparing objects, updated!

Comment (audrium) [reply reana-ui/src/pages/workflowList/WorkflowList.js]: LGTM!
