### PR TITLE
wf-details: fix misplaced refresh button

### LINKED ISSUE #236: minor: workflow details page, loading icon is overlapping with steps count
On the right side, you can see a loading icon being displaced:

Screenshot 2022-03-10 at 16 24 06

Resolution: 1920x1200

### PR DESCRIPTION
**Pull request by mvidalgarcia**
closes #236

image

### CODE REVIEW

File: reana-ui/src/pages/error/NotFound.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ export default function NotFound() {
           <h2>Page Not Found</h2>
           <p>The page you are looking for could not be found.</p>
           <Link to="/">
-            <Button primary>Go to Home</Button>
+            <Button primary>Go to Home page</Button>
```
Comment (tiborsimko) [inline reana-ui/src/pages/error/NotFound.js:25]: `s/Home/home/`  to use regular phrase capitalisation.

I would even use "Page not found" (BrE) rather than "Page Not Found" (AmE).

Comment (audrium) [reply reana-ui/src/pages/error/NotFound.js]: I guess it's a matter of taste, for me the page looked better without these changes

**Review by audrium — APPROVED** [review]
Fix works nicely
